### ISSUE TITLE
Can't load SF Pro Text Bold in canvas

### ISSUE THREAD

**Issue by brianlovin** [brianlovin/figma-dominant-color-toolkit#1]
I need to know what fonts are available on the machine before creating the labels in the palette...

**Comment by Andreslav** [comment]
@brianlovin try `listAvailableFontsAsync()` https://www.figma.com/plugin-docs/api/figma/#listavailablefontsasync

**Comment by brianlovin** [comment]
Shipped, thanks for the pointer @Andreslav!
