### ISSUE TITLE
Can’t apply color to Frame layer

### ISSUE THREAD

**Issue by ImperialBebek** [brianlovin/figma-dominant-color-toolkit#45]
I have a Frame layer with Gradient color and the Autolayout On.

My first thought that it won’t apply to a gradient but It works on a normal Shape layer.

**Comment by brianlovin** [comment]
@ImperialBebek I'm not sure I understand what your question is, or what this issue is for.

**Comment by ImperialBebek** [comment]
Oh I’m sorry if I didn’t say it clearly.

The issue I got is the plugin is not working on a “Frame” layer.
It does on a Shape layer though.

I’m not sure this is an issue or not so let me know.

**Comment by brianlovin** [comment]
Ah yeah that's probably a bug from before they changed frame behaviors in the Autolayout ship. Thanks!
